# Generated by Django 4.2.7

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Задължително. Валиден имейл адрес.', max_length=254, unique=True, verbose_name='имейл адрес')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='име')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='фамилия')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='телефон')),
                ('role', models.CharField(choices=[('citizen', 'Гражданин'), ('operator', 'Оператор'), ('technician', 'Техник'), ('admin', 'Администратор')], default='citizen', max_length=20, verbose_name='роля')),
                ('is_staff', models.BooleanField(default=False, help_text='Определя дали потребителят може да влиза в админ панела.', verbose_name='staff статус')),
                ('is_active', models.BooleanField(default=True, help_text='Определя дали потребителят е активен.', verbose_name='активен')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата на регистрация')),
                ('email_notifications', models.BooleanField(default=True, help_text='Получаване на известия по имейл', verbose_name='имейл известия')),
                ('sms_notifications', models.BooleanField(default=False, help_text='Получаване на SMS известия', verbose_name='SMS известия')),
                ('push_notifications', models.BooleanField(default=True, help_text='Получаване на push известия', verbose_name='push известия')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'потребител',
                'verbose_name_plural': 'потребители',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='адрес')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='град')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='пощенски код')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='avatars/', verbose_name='аватар')),
                ('bio', models.TextField(blank=True, verbose_name='биография')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='географска ширина')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='географска дължина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='създаден на')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновен на')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='потребител')),
            ],
            options={
                'verbose_name': 'потребителски профил',
                'verbose_name_plural': 'потребителски профили',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заглавие')),
                ('message', models.TextField(verbose_name='съобщение')),
                ('notification_type', models.CharField(choices=[('info', 'Информация'), ('warning', 'Предупреждение'), ('alert', 'Тревога'), ('success', 'Успех'), ('error', 'Грешка')], default='info', max_length=20, verbose_name='тип известие')),
                ('is_read', models.BooleanField(default=False, verbose_name='прочетено')),
                ('link', models.URLField(blank=True, verbose_name='връзка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='създадено на')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='прочетено на')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='потребител')),
            ],
            options={
                'verbose_name': 'известие',
                'verbose_name_plural': 'известия',
                'ordering': ['-created_at'],
            },
        ),
    ]
