# Generated by Django 4.2.7

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='име')),
                ('sensor_type', models.CharField(choices=[('flow', 'Разходомер'), ('pressure', 'Налягане'), ('quality', 'Качество на водата'), ('level', 'Ниво на резервоар'), ('temperature', 'Температура'), ('leak', 'Детектор за теч')], max_length=20, verbose_name='тип')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен'), ('maintenance', 'В поддръжка'), ('error', 'Грешка')], default='active', max_length=20, verbose_name='статус')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='географска ширина')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='географска дължина')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='адрес')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='район')),
                ('min_value', models.FloatField(default=0, verbose_name='минимална стойност')),
                ('max_value', models.FloatField(default=100, verbose_name='максимална стойност')),
                ('threshold_warning', models.FloatField(blank=True, null=True, verbose_name='праг за предупреждение')),
                ('threshold_critical', models.FloatField(blank=True, null=True, verbose_name='критичен праг')),
                ('serial_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='сериен номер')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='производител')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='дата на инсталация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='създаден на')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновен на')),
                ('last_reading_at', models.DateTimeField(blank=True, null=True, verbose_name='последно четене')),
            ],
            options={
                'verbose_name': 'сензор',
                'verbose_name_plural': 'сензори',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaterConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100, verbose_name='район')),
                ('date', models.DateField(verbose_name='дата')),
                ('hour', models.PositiveSmallIntegerField(default=0, verbose_name='час')),
                ('consumption_liters', models.FloatField(verbose_name='консумация (литри)')),
                ('avg_pressure', models.FloatField(blank=True, null=True, verbose_name='средно налягане')),
                ('avg_quality_score', models.FloatField(blank=True, null=True, verbose_name='среден коефициент на качество')),
                ('min_consumption', models.FloatField(blank=True, null=True, verbose_name='минимална консумация')),
                ('max_consumption', models.FloatField(blank=True, null=True, verbose_name='максимална консумация')),
                ('std_deviation', models.FloatField(blank=True, null=True, verbose_name='стандартно отклонение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='създадено на')),
            ],
            options={
                'verbose_name': 'консумация на вода',
                'verbose_name_plural': 'консумация на вода',
                'ordering': ['-date', '-hour'],
                'unique_together': {('district', 'date', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='стойност')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='мерна единица')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='време')),
                ('is_anomaly', models.BooleanField(default=False, verbose_name='аномалия')),
                ('anomaly_score', models.FloatField(blank=True, null=True, verbose_name='аномален резултат')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='сурови данни')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='dashboard.sensor', verbose_name='сензор')),
            ],
            options={
                'verbose_name': 'измерване',
                'verbose_name_plural': 'измервания',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заглавие')),
                ('description', models.TextField(verbose_name='описание')),
                ('incident_type', models.CharField(choices=[('burst_pipe', 'Спукана тръба'), ('major_leak', 'Голям теч'), ('pump_failure', 'Неизправност на помпа'), ('contamination', 'Замърсяване'), ('maintenance', 'Планирана поддръжка'), ('power_outage', 'Прекъсване на тока'), ('other', 'Друго')], max_length=20, verbose_name='тип инцидент')),
                ('status', models.CharField(choices=[('reported', 'Докладван'), ('investigating', 'В проверка'), ('in_progress', 'В процес на отстраняване'), ('resolved', 'Разрешен'), ('cancelled', 'Отменен')], default='reported', max_length=20, verbose_name='статус')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='географска ширина')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='географска дължина')),
                ('address', models.CharField(max_length=255, verbose_name='адрес')),
                ('district', models.CharField(max_length=100, verbose_name='район')),
                ('affected_area_radius', models.FloatField(default=500, verbose_name='радиус на засегнатата зона (м)')),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='докладван на')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='започнал на')),
                ('estimated_resolution', models.DateTimeField(blank=True, null=True, verbose_name='прогнозно разрешаване')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='разрешен на')),
                ('affected_users', models.PositiveIntegerField(default=0, verbose_name='засегнати потребители')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='прогнозна стойност')),
                ('image', models.FileField(blank=True, null=True, upload_to='incidents/', verbose_name='снимка')),
                ('is_public', models.BooleanField(default=True, verbose_name='публичен')),
                ('is_featured', models.BooleanField(default=False, verbose_name='избран')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='създаден на')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновен на')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL, verbose_name='възложен на')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL, verbose_name='докладван от')),
            ],
            options={
                'verbose_name': 'инцидент',
                'verbose_name_plural': 'инциденти',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заглавие')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('anomaly_type', models.CharField(choices=[('leak', 'Теч'), ('pressure_drop', 'Спад на налягане'), ('pressure_spike', 'Скок на налягане'), ('quality_issue', 'Проблем с качеството'), ('high_consumption', 'Висока консумация'), ('low_consumption', 'Ниска консумация'), ('sensor_malfunction', 'Неизправност на сензор'), ('other', 'Друго')], max_length=30, verbose_name='тип аномалия')),
                ('severity', models.CharField(choices=[('low', 'Ниска'), ('medium', 'Средна'), ('high', 'Висока'), ('critical', 'Критична')], max_length=20, verbose_name='тежест')),
                ('status', models.CharField(choices=[('detected', 'Открита'), ('investigating', 'В проверка'), ('confirmed', 'Потвърдена'), ('resolved', 'Разрешена'), ('false_positive', 'Фалшива тревога')], default='detected', max_length=20, verbose_name='статус')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='географска ширина')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='географска дължина')),
                ('affected_area', models.FloatField(blank=True, null=True, verbose_name='засегната площ (кв.м)')),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='открита на')),
                ('confidence', models.FloatField(help_text='ML увереност в процента', verbose_name='увереност (%)')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='разрешена на')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='бележки за разрешаване')),
                ('estimated_start', models.DateTimeField(blank=True, null=True, verbose_name='прогнозно начало')),
                ('estimated_end', models.DateTimeField(blank=True, null=True, verbose_name='прогнозен край')),
                ('estimated_affected_users', models.PositiveIntegerField(default=0, verbose_name='засегнати потребители')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='създадена на')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновена на')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_anomalies', to=settings.AUTH_USER_MODEL, verbose_name='разрешена от')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='dashboard.sensor', verbose_name='сензор')),
            ],
            options={
                'verbose_name': 'аномалия',
                'verbose_name_plural': 'аномалии',
                'ordering': ['-detected_at'],
            },
        ),
    ]
