# Generated by Django 4.2.7 on 2026-04-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['sensor', '-timestamp'], name='dashboard_s_sensor__ca22d4_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['is_anomaly'], name='dashboard_s_is_anom_e300d6_idx'),
        ),
    ]
