# Generated by Django 4.2.7

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(blank=True, max_length=150, verbose_name='име на подател')),
                ('reporter_email', models.EmailField(blank=True, verbose_name='имейл на подател')),
                ('reporter_phone', models.CharField(blank=True, max_length=20, verbose_name='телефон на подател')),
                ('title', models.CharField(max_length=200, verbose_name='заглавие')),
                ('description', models.TextField(verbose_name='описание')),
                ('category', models.CharField(choices=[('leak', 'Теч'), ('burst_pipe', 'Спукана тръба'), ('pressure_low', 'Ниско налягане'), ('pressure_high', 'Високо налягане'), ('water_quality', 'Качество на водата'), ('no_water', 'Няма вода'), ('sewage', 'Канализационен проблем'), ('hydrant', 'Пожарен хидрант'), ('meter', 'Водомер'), ('other', 'Друго')], max_length=20, verbose_name='категория')),
                ('status', models.CharField(choices=[('pending', 'Чакащ'), ('investigating', 'В проверка'), ('confirmed', 'Потвърден'), ('in_progress', 'В процес'), ('resolved', 'Разрешен'), ('rejected', 'Отхвърлен')], default='pending', max_length=20, verbose_name='статус')),
                ('priority', models.CharField(choices=[('low', 'Нисък'), ('medium', 'Среден'), ('high', 'Висок'), ('urgent', 'Спешен')], default='medium', max_length=20, verbose_name='приоритет')),
                ('address', models.CharField(max_length=255, verbose_name='адрес')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='район')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='географска ширина')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='географска дължина')),
                ('image', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='снимка')),
                ('notes', models.TextField(blank=True, verbose_name='вътрешни бележки')),
                ('estimated_start', models.DateTimeField(blank=True, null=True, verbose_name='прогнозно начало')),
                ('estimated_end', models.DateTimeField(blank=True, null=True, verbose_name='прогнозен край')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='създаден на')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновен на')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='разрешен на')),
                ('is_public', models.BooleanField(default=True, verbose_name='публичен')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL, verbose_name='възложен на')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='потребител')),
            ],
            options={
                'verbose_name': 'сигнал',
                'verbose_name_plural': 'сигнали',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('pending', 'Чакащ'), ('investigating', 'В проверка'), ('confirmed', 'Потвърден'), ('in_progress', 'В процес'), ('resolved', 'Разрешен'), ('rejected', 'Отхвърлен')], max_length=20, verbose_name='стар статус')),
                ('new_status', models.CharField(choices=[('pending', 'Чакащ'), ('investigating', 'В проверка'), ('confirmed', 'Потвърден'), ('in_progress', 'В процес'), ('resolved', 'Разрешен'), ('rejected', 'Отхвърлен')], max_length=20, verbose_name='нов статус')),
                ('comment', models.TextField(blank=True, verbose_name='коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='създаден на')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='променен от')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='reports.report', verbose_name='сигнал')),
            ],
            options={
                'verbose_name': 'история на статус',
                'verbose_name_plural': 'история на статуси',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='съдържание')),
                ('is_internal', models.BooleanField(default=True, help_text='Вътрешните коментари не се показват на подателя на сигнала', verbose_name='вътрешен коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='създаден на')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновен на')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_comments', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.report', verbose_name='сигнал')),
            ],
            options={
                'verbose_name': 'коментар',
                'verbose_name_plural': 'коментари',
                'ordering': ['-created_at'],
            },
        ),
    ]
